name: Laravel MySQL CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u testuser --password=testpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, bcmath, curl, mysql, pdo_mysql

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set environment variables
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_USERNAME=testuser" >> .env
          echo "DB_PASSWORD=testpass" >> .env

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
